### ISSUE TITLE
The result

### ISSUE THREAD

**Issue by SunnysideBao** [huiminren/RobustVAE#2]
![genfid_eg](https://user-images.githubusercontent.com/39000707/95668367-97401200-0ba5-11eb-9819-a924cda52072.jpg)
I'm very glad to get your reply. The result of running according to the main program is as shown in the figure, but the effect is not ideal. What is the reason?

**Comment by SunnysideBao** [comment]
![recon_face](https://user-images.githubusercontent.com/39000707/95708002-bfa33b80-0c8d-11eb-8e83-7aaefe3407f2.jpg)
The result of running according to the main program is as shown in the figure, but the effect is not ideal. What is the reason?It has no de-noising effect.

**Comment by huiminren** [comment]
Hello, sorry for the late response. There was something wrong with our server and we still need several days to fix it. 
For your question, please make sure you have downloaded the full dataset of CelebA http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html and train with our model. We only upload sample images to the repo due to the space limit. The images you showed look like the input of the model and not the results. We provided three types of results, i.e., raw_face.jpg, recon_face.jpg and genfid_eg.jpg. 
I will let you know once our server works.
Thanks.

**Comment by huiminren** [comment]
> ![recon_face](https://user-images.githubusercontent.com/39000707/95708002-bfa33b80-0c8d-11eb-8e83-7aaefe3407f2.jpg)
> The result of running according to the main program is as shown in the figure, but the effect is not ideal. What is the reason?It has no de-noising effect.

Hello, the results are similar to the paper after re-run our code. From your two screenshots, I think you didn't use the full dataset from CelebA, thus didn't get the expected results. 
The 8 images here are the raw images which are our input and not the generated results. We did save some results, such as "raw_face.jpg", "recon_face.jpg" and "genfid_eg.jpg". You can check them after running the code. "genfid_eg.jpg" shows the denoised-generated results.
